### ISSUE TITLE
Filter out diet entries if their comment is ZK (zookeeper)

### ISSUE THREAD

**Issue by ColinKrist** [ohdzdev/NutritionSystem#24]
**Is your feature request related to a problem? Please describe.**
* When I am a kitchen person, I don't need to see diet entries that a zookeeper will handle preparing.

**Describe the solution you'd like**
* From diet plan entries that have comments with `ZK` we should filter those entries out from the list.

**Describe alternatives you've considered**
* Create new field in DB that is a boolean that does the same thing here. But instead of person entering ZK manually in the comments it's a checkbox on the comments form. @MitchellSlavik thoughts? We'd have to create a SP to look for ZK entries and do this for existing data, but it's a better long term solution.

**Additional context**

**Comment by MitchellSlavik** [comment]
Currently this could be solved by just entirely rewriting the kitchen page to use the stored procedures I wrote a while ago.
