### ISSUE TITLE
Foods missing from diet records

### ISSUE THREAD

**Issue by ohdzdev** [ohdzdev/NutritionSystem#58]
**Describe the bug**
Ingredient names are not showing up, either on individual diet records, or on prep screen. Diet records just have a list of amounts for invisible ingredients.

**To Reproduce**
1. Go to Diets, click any diet, see "Current Diet Plan"
2. Or, go to Kitchen, click Open Prep Screen, select any table, see list of diet amounts.

**Comment by MitchellSlavik** [comment]
Fixed database as the conversion program did not copy the food names properly
